Update webpay logo
TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest pull request #45
Opened 2020-12-29 18:01 UTC by gonzunigad

Update webpay logo

2020-12-29 18:05 UTC, afiebig requested changes
This is just a deletion. If this is really an update you are missing the new logo.

2020-12-29 19:53 UTC, gonzunigad commented
![image](https://user-images.githubusercontent.com/1103494/103310422-57dfcf80-49f6-11eb-8406-a505a3759236.png)

This is a modified image :)

2020-12-30 19:26 UTC, gonzunigad commented
@afiebig

2020-12-31 12:31 UTC, afiebig approved these changes

2020-12-31 12:57 UTC, merged